#pragma once

#define BUILD_DATE "Unknown"
#define BUILD_TIME "Unknown"
#define BUILD_HASH "Unknown"
#define BUILD_COMMIT_TIMESTAMP "Unknown"
#define BUILD_COMMIT_DATE "Unknown"
#define BUILD_COMMIT_TIME "Unknown"
#define BUILD_BRANCH "Unknown"
#define BUILD_PLATFORM "Unknown"
#define BUILD_TYPE "Unknown"
#define BUILD_CFLAGS "Unknown"
#define BUILD_CXXFLAGS "Unknown"
#define BUILD_LINKFLAGS "Unknown"
#define BUILD_SYSTEM "Unknown"
